// @ts-check
// Each top-level navbar entry has its own sidebar, autogenerated from
// the matching folder under docs/. Order and category labels come from
// _category_.json files inside each folder.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  about: [{ type: "autogenerated", dirName: "about" }],
  homelab: [{ type: "autogenerated", dirName: "homelab" }],
  work: [{ type: "autogenerated", dirName: "work" }],
  certifications: [{ type: "autogenerated", dirName: "certifications" }],
};

export default sidebars;
