// @ts-check
// Each top-level navbar entry has its own sidebar. We wrap the
// autogenerated tree in an explicit top-level category so breadcrumbs
// render as Home > Section > Subsection > Page (instead of Home > Page).
// Without the wrapper, the autogenerated dirName flattens out and the
// section name disappears from the breadcrumb trail.
//
// Each wrapper's link points at the section's index.mdx (slug = /<section>),
// so clicking the navbar item or the breadcrumb section name lands on
// the real section landing page. Docusaurus is smart enough to exclude
// the index doc from being listed twice in the sidebar items below.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  me: [
    {
      type: "category",
      label: "Me",
      link: { type: "doc", id: "me/index" },
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "me" }],
    },
  ],
  engineering: [
    {
      type: "category",
      label: "Engineering",
      link: { type: "doc", id: "engineering/index" },
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "engineering" }],
    },
  ],
  learn: [
    {
      type: "category",
      label: "Learn",
      link: { type: "doc", id: "learn/index" },
      collapsible: true,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "learn" }],
    },
  ],
};

export default sidebars;
