// @ts-check
// Each top-level navbar entry has its own sidebar, autogenerated from
// the matching folder under docs/. Order and category labels come from
// _category_.json files inside each folder.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  me: [{ type: "autogenerated", dirName: "me" }],
  engineering: [{ type: "autogenerated", dirName: "engineering" }],
  learn: [{ type: "autogenerated", dirName: "learn" }],
};

export default sidebars;
