---
# 1. Deployment for Portfolio Website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deploy
  namespace: web-development
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio-container
          image: cjoga/portfolio:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
            - name: VITE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: supabase-url
            - name: VITE_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: supabase-anon-key
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
# 2. Service to expose the Portfolio Deployment internally
apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  namespace: web-development
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
---
# 3. Traefik IngressRoute to expose the Service publicly via Cloudflare Tunnel
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio-public-ingress
  namespace: web-development
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cjoga.cloud`) || Host(`www.cjoga.cloud`)
      kind: Rule
      services:
        - name: portfolio-svc
          port: 80
